import NavBar from "@/components/navbar/NavBar";
import SlideMain from "@/components/slide-main/SlideMain";
import "./globals.css";
 // Asegúrate de incluir tu archivo CSS global
 import { Kanit } from 'next/font/google';

// Carga la fuente Kanit con los pesos deseados
const kanit = Kanit({
  subsets: ['latin'], // Puedes agregar más subsets si lo necesitas
  weight: ['400', '700'], // Define los pesos que vas a usar
  variable: '--font-kanit', // Define una variable CSS opcional
});



export const metadata = {
  title: "Taste Share",
  description: "Generated by create next app",
};

function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <NavBar />
        <SlideMain />
        <main>{children}</main>
      </body>
    </html>
  );
}


export default RootLayout;