export const metadata = {
    title: "Taste Share",
    description: "Generated by create next app",
    icons: {
      icon: "/logo_taste_share.png", // Ruta al logo dentro de la carpeta public
    },
  };